# Generated by Django 4.0.4 on 2022-10-19 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neonadmin', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('pincode', models.IntegerField()),
                ('locality', models.CharField(max_length=150)),
                ('addres', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=50)),
                ('landmark', models.CharField(default='', max_length=50)),
                ('alternatephone', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='neonlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=500)),
                ('blocked', models.CharField(default='F', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neonadmin.products')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neonuser.neonlogin')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('paymentMethod', models.CharField(max_length=150)),
                ('paymentId', models.CharField(max_length=200)),
                ('orderStatus', models.CharField(max_length=60)),
                ('amount', models.BigIntegerField()),
                ('orderedtime', models.DateTimeField(auto_now_add=True)),
                ('ShippingAddress', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='neonuser.address')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neonadmin.products')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neonuser.neonlogin')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neonadmin.products')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neonuser.neonlogin')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neonuser.neonlogin'),
        ),
    ]
