# Generated by Django 4.0.4 on 2022-10-27 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neonuser', '0002_alter_orders_orderedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderedtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 27, 10, 50, 4, 702851)),
        ),
    ]
