# Generated by Django 4.0.4 on 2022-10-27 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neonuser', '0005_alter_cart_less_alter_orders_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='finalamt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderedtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 27, 20, 24, 18, 306514)),
        ),
    ]
