# Generated by Django 4.0.4 on 2022-10-27 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neonuser', '0009_alter_orders_orderedtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='finalamt',
        ),
        migrations.AddField(
            model_name='cart',
            name='finalamt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderedtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 27, 20, 55, 40, 232164)),
        ),
    ]
