# Generated by Django 4.0.4 on 2022-10-31 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neonuser', '0011_alter_orders_orderedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderedtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 31, 15, 48, 20, 241984)),
        ),
    ]
