# Generated by Django 4.0.4 on 2022-11-10 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neonuser', '0015_alter_orders_orderedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='neonlogin',
            name='twofa',
            field=models.CharField(default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderedtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 10, 15, 10, 19, 215303)),
        ),
    ]
