# Generated by Django 4.0.8 on 2022-11-28 10:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neonadmin', '0008_alter_offers_catid_alter_offers_pid'),
        ('neonuser', '0021_alter_orders_orderedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderedtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 28, 15, 34, 52, 689305)),
        ),
        migrations.CreateModel(
            name='guestcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=250)),
                ('quantity', models.IntegerField(default=1)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neonadmin.products')),
            ],
        ),
    ]
