# Generated by Django 4.0.4 on 2022-10-19 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='banner/')),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='subcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(max_length=60)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neonadmin.categories')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('brand', models.CharField(max_length=60)),
                ('model_number', models.CharField(max_length=60)),
                ('price', models.BigIntegerField()),
                ('ram', models.CharField(default='null', max_length=10)),
                ('rom', models.CharField(default='null', max_length=10)),
                ('processor', models.CharField(default='null', max_length=50)),
                ('display', models.CharField(default='null', max_length=60)),
                ('description', models.CharField(max_length=500)),
                ('stock', models.BigIntegerField()),
                ('img1', models.ImageField(upload_to='products/')),
                ('img2', models.ImageField(upload_to='products/')),
                ('img3', models.ImageField(upload_to='products/')),
                ('img4', models.ImageField(upload_to='products/')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neonadmin.categories')),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neonadmin.subcategories')),
            ],
        ),
    ]
