# Generated by Django 4.0.4 on 2022-10-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neonadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60)),
                ('discount', models.BigIntegerField()),
                ('discount_limit', models.BigIntegerField()),
                ('min_purchase_amt', models.BigIntegerField()),
            ],
        ),
    ]
