# Generated by Django 4.0.4 on 2022-10-29 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neonadmin', '0003_alter_products_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.FloatField()),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neonadmin.categories')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neonadmin.products')),
            ],
        ),
    ]
