# Generated by Django 4.0.4 on 2022-10-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neonadmin', '0004_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='max_limit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
