# Generated by Django 4.0.4 on 2022-10-31 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neonadmin', '0007_alter_offers_catid_alter_offers_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='catid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='neonadmin.categories'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='pid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='neonadmin.products'),
        ),
    ]
